### ISSUE TITLE
登录后观看几个视频后会报空指针异常，退出登录才能观看

### ISSUE THREAD

**Issue by JunRzz** [techGay/v9porn#54]
### 运行环境 ###

- [x] 手机型号：小米Mix 2S
- [x] 系统版本：Android 8.0.0
- [x] APP 版本：`1.0.6`

#### 问题截图: ####
![screenshot_2018-09-01-08-28-01-618_com u9porn](https://user-images.githubusercontent.com/36223028/44941593-84a65c80-add3-11e8-918e-d30863ae6833.png)

#### 自己尝试了哪些，结果如何? ####
尝试清除缓存，重新登录，还是失败。必须在非登录情况下才能观看视频

**Comment by Archive94** [comment]
@techGay

**Comment by Archive94** [comment]
@techGay 
```
09-01 21:11:31.393 27037-27037/com.u9porn W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference
09-01 21:11:31.394 27037-27037/com.u9porn W/System.err:     at com.u9porn.parser.ParseV9PronVideo.parseVideoPlayUrl(ParseV9PronVideo.java:212)
        at com.u9porn.data.network.AppApiHelper$9.apply(AppApiHelper.java:235)
        at com.u9porn.data.network.AppApiHelper$9.apply(AppApiHelper.java:232)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
09-01 21:11:31.395 27037-27037/com.u9porn W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableRetryWhen$RepeatWhenObserver.subscribeNext(ObservableRetryWhen.java:150)
        at io.reactivex.internal.operators.observable.ObservableRetryWhen.subscribeActual(ObservableRetryWhen.java:60)
        at io.reactivex.Observable.subscribe(Observable.java:12005)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-01 21:11:31.396 27037-27037/com.u9porn W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by techGay** [comment]
就在ParseV9PronVideo.java:212那行了，解析不到视频标签，但是为什么返回的html没有视频的连接，这就不知道了，也许和你帐号有关，可以把返回的html打印出来看看有什么信息

**Comment by Archive94** [comment]
@techGay 请求回来的html稍后我发你邮箱

**Comment by techGay** [comment]
ok

**Comment by techGay** [comment]
原因就在这：你的级别是1级，你每天可以观看20部视频，你可以通过赚取积分来升级

---不确定是不是针对帐号的限制，如果是，那暂时没办法，多注册几个帐号换着看试试吧

**Comment by Archive94** [comment]
@techGay 看起来是的，登录了账号就会根据账号观看的视频数量进行限制，退出账号之后，随机ip就生效了

**Comment by Archive94** [comment]
@techGay 麻烦看下pr，解决了这个问题
[pull request](https://github.com/techGay/v9porn/pull/55)

**Comment by Marblog** [comment]
来个地址啊

**Comment by wangzhanxian** [comment]
地址是什么

**Comment by wkmcyz** [comment]
≥......
